### ISSUE TITLE
Don't open GUI from the main thread.

### ISSUE THREAD

**Issue by Aaron1011** [Rikmuld/MC-RMCore#1]
Currently, [`PacketOpenGui#handlePacket` directly opens a GUI](https://github.com/Rikmuld/MC-RMCore/blob/5c5d42f3fb248efe2dff7008f3fccca0c2b43130/scala/com/rikmuld/corerm/network/packets/PacketOpenGui.scala#L50). However, this method is run on a Netty thread, which means that any interaction with the game must be scheduled on the main thread via `MinecraftServer#addScheduledTask`.

**Comment by rikmuld** [comment]
Ah, I didn't know, thanks for noting, this should be fine then?

**Comment by Aaron1011** [comment]
Looks good to me!

**Comment by bentterp** [comment]
Confirmed working. Thank you so very much, Minecraft would not be the same without camping

**Comment by MagmaSlime123** [comment]
> Ah, I didn't know, thanks for noting, this should be fine then?

You have a new issue.
